name: Bug report
description: File a bug with markview
title: '[ 🐞 Bug ] '
assignees:
  - OXY2DEV
body:
  - type: checkboxes
    id: issue-conditions
    attributes:
      label: 'Before reporting:'
      description: >-
        These are **requirements** and failing to fulfill them will result the
        issue to be closed.
      options:
        - label: Ensure that the issue is reproducable on the main branch.
          required: true
        - label: Ensure that there isn't an issue on this(either open or closed).
          required: true
  - type: textarea
    id: issue-desc
    attributes:
      label: 'Problem:'
      description: >-
        Describe the current behavior(images, gif, videos & logs) may be
        attached.
      placeholder: A description of the issue...
    validations:
      required: true
  - type: textarea
    id: issue-repro
    attributes:
      label: 'Steps to reproduce the issue:'
      description: |
        ### Things to check before opening an issue:

        - Ensure that you don't have other `markdown` plugins enabled(unless
        it's a comparability issue with that plugin).

        - Ensure that you are using the **latest version** of the plugin.

        - Ensure that your `Neovim` version is **>=0.10**.

        - Ensure that you have the correct `tree-sitter` parsers
        installed(markdown, markdown_inline & html).
      placeholder: nvim
    validations:
      required: true
  - type: textarea
    id: issue-expected
    attributes:
      label: 'Expected behavior:'
      description: Describe what should've happened.
      placeholder: Markview should've...
  - type: input
    id: issue-nvim_v
    attributes:
      label: 'Neovim version:'
      description: Neovim version.
      placeholder: nvim -v
    validations:
      required: true
